# Generated by Django 5.1.5 on 2025-04-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_userprofile_assigned_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='assigned_staff',
        ),
        migrations.AddField(
            model_name='appointment',
            name='assigned_staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
